### ISSUE TITLE
onTerminate() is not called on production devices

### ISSUE THREAD

**Issue by LouisCAD** [afollestad/inquiry#4]
Hi!
Your library `README.md` shows an Application class overriding onTerminate()`` method,
 but the doc says:
> This method is for use in emulated process environments.  It will never be called on a production Android device, where processes are removed by simply killing them; no user code (including this callback) is executed when doing so.

So you should remove the snippet but I have to ask: Is it a problem?

Doesn't Android release all resources when shutting down the entire app? Is there real side effects if not calling `Inquiry.deinit();` after Android killed completely the app?

Should we call this before, when the last task is closed for example? (I don't know how to detect it properly though)

Thanks, and have a nice day!

Louis CAD

**Comment by afollestad** [comment]
Good find, I'll change that around.

But yes, it can be a problem. Garbage collectors aren't perfect, sometimes you can get memory that hangs around too long if you don't explicitly say you're no longer using it. That's why libraries like [LeakCanary](https://github.com/square/leakcanary) (from square) exist.
